// Chapter 9: Uranium

#import "../template.typ": recipe

= URANIUM

#figure(kind: "subtitle", supplement: none, numbering: none)[The radioactive red.]

The history of uranium based red glazes is as a matter of fact of course a young but also a rather short one. Young because it developed only after the discovery of the element uranium and after the different oxides were put into operation. Short because one distinguished on one hand also the negative and dangerous properties with regard to radiation phenomena when people are exposed to these components and on the other hand governments also blocked the various applications, this in favour of the application for the investigations in the atomic energy area.

Uranium is called after Uranus, in the Greek mythology the father of the goddess Aphrodite. The name for the element was chosen because of the planet which was discovered some years before by the Englishman W. Herschel in 1781.

The German chemist and mineralogist Martin Heinrich Klaproth (1743 -- 1817) must be honoured as the discoverer of the new element. He was first a pharmacist and a chemistry master before he became a professor at the University of Berlin. He did much work on the analyses of rocks. As a result of this he found several new elements such as uranium but also zirconium (1789), titanium (1795) and cerium (1803). He also discovered strontium as well and studied tellurium. By that time one called the component as representative in pitchblende uranium, while later on it became clear that it was the oxide form $"U"_3"O"_8$ which was present in pitchblende or uranite.

Although the official discovery of the element took place on the eve of imposing developments in both physics and chemistry, one had already found some pieces of yellow coloured glass containing about 1% of uranium near Naples. These pieces could be dated as from AD 79.#footnote[CRC, Handbook of Chemistry and Physics, 58#super[th] edition, 1977/1978.]

The developments with respect to uranium went very fast after the discovery of its radiation properties. Wilhelm Conrad Röntgen, a German physicist, did an investigation during 1895 about the penetration of cathode-beams when he did his great discovery of the special radiation which is called after him. He proved that such radiation had other properties than the cathode-beams.

The French physicist Henri Bequerel studied this important phenomenon and investigated the possibility of a relation between the origin of the X-rays and fluorescence phenomenae. During this investigation he discovered the radiation of uranium salts. As the successor of his father and grandfather in the position of professor in the Muséum d'histoire naturelle (Paris), he studied the radiation of uranium in a magnetic field, generated by an electromagnet. This studies resulted in the appointment that the radiation was a property of the uranium atom and valid for all the uranium components.

Maria Curie Sklodowska continued in this field and discovered that uranium was not the only element showing radiation properties. Together with her husband and well known French physicist Pierre Curie she established that the radiation was not an exclusive property of uranium and that also thorium showed this radiation. During further investigations of minerals they found that pitchblende showed a much stronger radiation than the quantities of uranium or thorium did presume. This led to the discovery of polonium and finally to radium in 1898.#footnote[Eve Curie. 'Madame Curie, haar leven en werk', 5#super[th] edition, 1938 H.F.Leopolds Uitgeversmaatschappij n.v. Den Haag.]

The importance of these new materials was soon distinguished. The main mineral and source for uranium was and still is pitchblende, also called uranite: $"U"_3"O"_8$. Uranium occurs however also in much other minerals such like carnotite (an uranium potassium vanadate), in autunite (a calcium uranyl-phosphate), in uranophane (a hydrated uranium calcium silicate), in curite (a hydrated lead urinate), in torbernite (a hydrated copper uranyl phosphate and many others.#footnote[A. Esme. 'Natural sources of uranium'. Argile, no. 189, 1936.]

Intensive searching programmes showed that the element is not as rare as it was once thought. Because of its importance in the field of the atomic energy one has searched very intensively to uranium containing minerals. Some main and well known uranium deposits are at Sjinkolobwe (Zaire), Jáchymov (Czech Rep.), Cornwall (England), Colorado (USA), near Great Bear Lake and Athabasca Lake (Canada), Witwatersrand (South Africa), Rum Jungle and Isa Mount (Australia), Bihar (India) and Poços de Caldas (Brasil).#footnote[Anon. 'Uranium -- some characteristics and sources'. Chem. Age, 53, 1945.]

All these deposits are mainly explored with regard to the economical value of uranium. One of the most important applications is its use in electrical power plants. It may be clear that this application is out of the scope of this publication. The point however where these two items do come together again is at the developments which mention the use of a glass in a unit for the melting-in of nuclear waste material.#footnote[L. D. Pye. 'Glass; a possible solution to nuclear waste problem'. Ceramic Industry, February 1983.]#footnote[Wilfried C. Heimerl. US patent 4 341 547. 'Apparatus for enclosing highly radioactive waste material in a glass smelt'.]

Other than some early findings of uranium containing glass through which an early application is known, a deliberated use of uranium containing minerals was uncommonly limited. The application of several uranium salts in the glass#footnote[J. M. Stevels; F. A. Kröger; T. P. J. Botden. 'Fluorescence of hexavalent uranium in glass'. Philips Research Reports, 3 (1) 46-48, 1948.] and ceramic industry came slightly into fashion during the first half of the 20#super[th] century. There are however not so many publications available as far as the ceramic sphere is concerned. An article of Charles F. Binns and Frobisher Lyttle#footnote[Charles F. Binns; Frobisher Lyttle. Journal of the Am. Cer. Society, no.11, 1920.] published in 1920 mention some compositions for uranium red glazes. As uranium source they mentioned sodium uranate ($"Na"_2"U"_2"O"_7$). The glazes, with 20 and 37 % $"Na"_2"U"_2"O"_7$ resp., developed a bright cinnabar red at a temperature of SK 04a (1020 °C). The base glaze was a lead alumina silicate with only an introduction of some potassium and zinc oxide in the $"R"_2"O" \/ "RO"$ group.

#recipe[
  Another article was published by Zimmermann#footnote[Zimmermann. 'Klei', no.20, 1927.]. He started with a simple lead-alumina-silicate with the following composition:

  #align(center,
    table(
      columns: (auto, auto, 2em, auto, auto, 2em, auto, auto),
      stroke: none,
      align: (left, right, center, left, right, center, left, right),
      [$"PbO"$], [1.000], [], [$"Al"_2"O"_3$], [0.175], [], [$"SiO"_2$], [0.850]
    )
  )
]

As a recommendation he indicated that the $"SiO"_2$ content may not exceed an amount of 1.0 according to the Seger formula. The influence of different compounds in the $"R"_2"O" \/ "RO"$ group was also studied. For these trials he used 20 parts of $"Na"_2"U"_2"O"_7$ to 100 parts of glaze.

Arnulf Holl#footnote[Arnulf Holl. 'Keramos', 1930.] studied also the rule of the body composition and found the negative influence of high calcium containing bodies with regard to the development of the red colour. A notable fact to be recorded is that he used an amount of 18 to 21 % of uranium nitrate as colouring compound. Other authors, among them the German Hans Eska, warned against the use of this soluble uranium salt. The preparation of the glaze with this soluble component and the handling of the glazed articles by hand are reasons that a direct contact with this toxic element and the skin is almost unavoidable. The negative influence of calcium oxide on the red colour is in contradiction with the results of other investigators.

One of the most comprehensive and detailed studies was published in 1933 by Hans Eska#footnote[Hans Eska. 'Wetterfeste uranrote Glasuren'. Sprechsaal, no.4, 1933.]. In this publication called 'Wetterfeste uranrote Glasuren' ('Weather resistant uranium red glazes') he described the best possible glaze compositions to obtain resistant red uranium glazes. He mentioned the application of uranium nitrate, as soluble salt, very injudicious. He also turned down the argument that this particular uranium source should be cheaper. In his investigation he indicated the influences of modifications in the $"R"_2"O" \/ "RO"$, $"R"_2"O"_3$ and $"RO"_2$ groups on the colour, gloss, craze resistance and weather resistance.

As a base glaze composition he used a fritted lead meta silicate, completed with components as $"BaO"$, $"ZnO"$, $"CaF"_2$, $"MgO"$, $"Na"_2"O"$ (as sodium uranate), $"K"_2"O"$ and $"B"_2"O"_3$ also fritted, $"Al"_2"O"_3$ and $"UO"_3$ as uranium oxide $"U"_3"O"_8$.

The trials were fired in a brown coal fired muffelkiln at SK 08a (940 °C) and SK 05a (1000 °C). Heating up took 26 hours and the cooling 50 hours.

#recipe[
  One of the tests applied after the firing was a test with hydrochloric acid. The results were classified in 7 groups ranging from 'not attacked' to 'completely affected'. Glazes with only a variation in the $"SiO"_2$ content according to the formula:

  #align(center,
    table(
      columns: (auto, auto, 2em, auto, auto, 2em, auto, auto),
      stroke: none,
      align: (left, right, center, left, right, center, left, right),
      [$"PbO"$], [1.00], [], [$"Al"_2"O"_3$], [0.10], [], [$"SiO"_2$], [0.80 -- 1.60],
      [], [], [], [$"UO"_3$], [0.20], [], [], []
    )
  )

showed an improved resistance with an increasing $"SiO"_2$ content. The colour of these glazes was red.

]

If part of the lead content was replaced by barium oxide (0.1 mol and 0.2 mol resp.) the colour changed more towards orange-red colour tones. While the surface became more matt, craze resistance worsened, but the weather resistance should improve.

The introduction of $"ZnO"$ (0.1 mol and 0.2 mol resp.) resulted in more bright red glazes and even more bright with an increasing $"SiO"_2$ content. As best composition is mentioned 0.1 mol $"ZnO"$ in combination with 1.4 mol $"SiO"_2$. Those glazes showed a high gloss but the resistance was bad.

$"CaO"$ was applied and introduced as $"CaF"_2$ because this Ca-compound showed the best results if several Ca containing materials were compared. The calcium fluoride had a positive effect on the red colour development and also on the weather resistance.

A partly replacement of lead by magnesium oxide resulted also in red colours but the properties with regard to craze- and weather resistance worsened.

A partly replacement of lead by potassium resulted in more crazing while it also became more difficult to obtain a reasonable weather resistance. The red colour developed well but in the red appeared yellow spots.

Sodium had in common with potassium that it had a negative influence on the red colour development especially at higher temperatures. A good red colour however was obtained with a $"Na"_2"O"$ content of 0.05 mol with at the same time a $"SiO"_2$ content of not lower as 1.20 mol. An increased $"Na"_2"O"$ content till 0.10 mol required a $"SiO"_2$ content 1.20 mol or preferably somewhat lower. The sodium-lead uranium glazes had a strong disposition to crazing and good weather resistant glazes were not obtained.

#recipe[
  In summary it was concluded that good resistant uranium red glazes could be obtained with compositions between:

  #align(center,
    table(
      columns: (auto, auto, 2em, auto, auto, 2em, auto, auto),
      stroke: none,
      align: (left, right, center, left, right, center, left, right),
      [$"PbO"$], [0.85 -- 0.90], [], [$"Al"_2"O"_3$], [0.10], [], [$"SiO"_2$], [1.20 -- 1.60],
      [$"BaO"$], [0.15 -- 0.10], [], [], [], [], [], [],
      [$"CaF"_2$], [0.15 -- 0.10], [], [], [], [], [], [],
      [$"K"_2"O"$], [0.15 -- 0.10], [], [], [], [], [], [],
    )
  )
]

The influence of metal oxides such as $"CuO"$, $"CoO"$, $"Mn"_2"O"_3$, $"Fe"_2"O"_3$ and $"Sb"_2"O"_3$ on the colour development was also ascertained. The main conclusion was that these oxides destroyed the original uranium orange or red colour, but that sometimes colour effects were created which were impossible to obtain with more conventional (and cheaper) stains.

Another interesting but also rather compendious article was published in 1934 by Karl Kautz#footnote[Karl Kautz. 'The effect of glaze composition upon the colors produced by Sodiumuranate'. Journal of the Am. Cer. Society, January, 1934.]. He used $"Na"_2"O" dot 2"UO"_3 dot 6"H"_2"O"$ as colorant and studied the influence of glaze components on the development of specific colours. As a result he mentioned for a variety of colours the best possible glaze compositions.

#recipe[
  A 'pleasing red glaze of this type with a crystalline structure' could be obtained with the following glaze composition:

  #align(center,
    table(
      columns: (auto, auto, 2em, auto, auto, 2em, auto, auto),
      stroke: none,
      align: (left, right, center, left, right, center, left, right),
      [$"Na"_2"O"$], [0.10], [], [$"UO"_3$], [0.20], [], [$"SiO"_2$], [2.00],
      [$"PbO"$], [0.90], [], [], [], [], [], []
    )
  )
]

The remark that this glaze was only used to produce 'a few small pieces of art ware' is significant in respect of the stability and reproducibility of this red coloured glaze.

Franz Eggert#footnote[Franz Eggert. 'Beeinflussung der tomatenrote Farbe von Uranglasuren durch Zusätze'. Glas-Email-Keramo-Technik, März, 1951.] published an article in 1951 about the affecting of the tomato-red uranium glazes. His base glaze was a lead alumina silicate in combination with black $"UO"_3$ as colouring component, this to avoid the simultaneously introduction of sodium. He concluded among other things that in general all the glazes showed as a matter of fact different coloured layers. A first layer with a notable influence of the body; a middle layer and the top layer which was in most cases responsible for the final colour tone. Some remarks out of this publication are worthwhile to mention in respect of the realization of red colours.

An addition of 10 % of zinc oxide resulted in a colour shift towards more blood red.

5 % of lithium carbonate resulted in a dark-brown coloured first layer; a yellow-transparent middle layer and a dark blood-red top layer.

However, and as also reported in other publications, an addition of 2 % of beryllium carbonate should create the best possible and brightest tomato red uranium glazes.

F. H. Norton#footnote[F. H. Norton. 'Elements of Ceramics'. Addison-Wesley Press Inc., Mass. USA, 1952.] mentioned in 1952 the calcium and sodium uranates as suitable for the development of brilliant red, orange and yellow colours but pointed also out that 'present restrictions make their use in ceramics impossible'.

Two articles of Fritz Jochmann#footnote[Fritz Jochmann. 'Uran im Glass, als färbendes Metaloxyd und radioaktives Element'. Glas-Email-Keramo-Technik, May, 1958.]#footnote[Fritz Jochmann. 'Uran für die Glas- und keramische Industrie'. Glas-Email-Keramo-Technik, November, 1959.] published in 1958 and 1959 respectively are given some more information about the reactions with uranium compounds in glass. Glasses, no matter which composition, coloured with the normal available uranium compounds, resulted in yellowish-greenish fluorescence when melted under oxidizing conditions Reducing conditions resulted in a smoke-like greyish brown. In these cases he drew a parallel between copper-ruby caused by (reduced) copper in a colloidal state. The greyish-brown colour developed under reducing conditions should be created by uranium, also in a colloidal state.

An investigation to the radioactivity of the uranium glasses of his study was subject of the second part of the first publication. Concluded was e.g. that the glass composition as such had absolutely no influence on the radiation. Also the manufacturing procedures of the glasses (melting at rather high temperatures) did not influence the radiation. The only measure for radiation was the amount of uranium in the glass. Measuring the radiation of a glass composition before and after melting showed no noticeable differences if one made a correction for the melting weight factor. This factor must be understand as a difference in weight between a mix of raw materials and the weight of the same mix after melting, not involving the practical looses during melting.

Although the author pointed out the risks for the workers health when applying these compounds, he indicated in his second article that the compounds in question were available again when one had a special allowance and if it were materials without the for fission necessary $"U"^235$. This point of view can be considered as overtaken. To the more recent regulations in this respect we will revert later on.

Lehnhäuser#footnote[W. Lehnhäuser. 'Glasuren und ihre Farben'. Wilhelm Knapp Verlag, Germany, 1959.] listed the uranium compounds as colouring compounds for glazes in 1959. Although he indicated that these particular colouring compounds were expensive, he gave no special restrictions for their use. For a good uranium red glaze he recommended a $"SiO"_2$ content between 0.4 mol as a minimum and 1.3 mol as a maximum. Other glaze components should be only $"Al"_2"O"_3$ and $"PbO"$. As colouring component was applied an addition of 20 % (sodium) urinate. An oversaturation should result in a uranium-aventurine glaze, analogous to the iron-aventurines. The influence of common used alkaline earth components is also mentioned. The remark that the uranium compounds are toxic and must be treated as lead is nowadays a too brief information regarding the important radiation phenomenae for one's health.

Another application of uranium compounds and mentioned by Viehweger#footnote[Viehweger. 'Rezeptbuch für Glasuren + Farben'. Verlag des Sprechsaal, Müller&Schmidt, Coburg, Germany, 1959.] is in compositions for lustres. These type of lustres are the resinate salts of metal oxides dissolved in volatile essential oils. The preparation of this type of lustres is a very special one and requires an experience to a high degree.

For a golden yellow luster one made e.g. first a uranium resinate (a mixture of uranium nitrate and soft soap in the ratio 1: 1). This uranium resinate is then applied with colophony, benzene and oil of lavender. In the same book are also mentioned some glaze compositions which have sodium uranate in their composition. These glazes should realize a dark salmon coloured glaze. No special restrictions are given for the application of these compounds in respect of the harmful properties for the human health, except the information that the uranium compounds may not be used anymore in the ceramic industry.

The fact that these compounds are no longer applied in the ceramic sphere is mainly due to the very severe regulations and that those compounds must be registered because of its radioactivity. The radiation consists in fact of three different kinds of radiation. The $alpha$ parts consists of 2 protons and 2 neutrons. The radiation has only a reach of 5 cm and cannot pass the human skin. The $beta$ parts are in fact a fast moving electron. They have a reach of roughly 1 meter. The third kind of radiation is formed by the $gamma$ parts which are comparable with X-rays. This kind of radiation can only be stopped by thick walls of concrete or lead. This radiation is the cause of the so-called radiation disease.

The literature indicates that the characteristics of uranium red glazes are based upon the formation of lead-uranate: $"PbO" dot 2"UO"_3$. This is the reason that only a lead silicate or lead-alumina-silicate forms a suitable base glaze. The firing stability of these glazes was however rather limited. The available literature mentions in general glazes which develop a red colour at temperatures ranging from roughly 900 °C till 1020 °C. The sensitivity for a not well balanced firing atmosphere was more than normal compared with other glaze systems. Only oxidizing firing conditions resulted in the required results. Also a slightly reducing atmosphere caused already colour deviations, in most cases to more brownish colour tones. Uranium glazes were also sensitive for influence of sulphur. An addition of barium carbonate helped to suppress the sensitiveness.

Another aspect which made the glazes less easy to apply was the fact that in many cases sodium uranate was used as the colouring compound. The high amount necessary for a sufficient colour development (between 15 and 25 %) gave the glazes an alkaline character with sometimes strong leaching phenomenae, resulting in settling-down problems. The use of setting-up agents was in most cases a necessity.

The sometimes varying quality grades of the uranium compounds was also reason for deviating colour shades. Together with the high price of the compounds and the meanwhile distinguished dangerous properties with regard to the radiation made the glazes not suitable for industrial use on a large scale. The restrictions were reasons that these glazes were mainly applied on a limited scale for small pieces of art ware. Various pieces of orange-red to red glazed ceramic pieces could be seen in various factory musea e.g. of the Konakovo Faience Factory in Konakovo (Russia).

For the lower temperatures (900 °C -- 960 °C) it was often advised to apply raw, unfritted glazes while for the higher temperatures (960 °C -- 1020 °C) some sources in the literature mention that for those cases fritted glazes would render better results.

A not proper glaze application often resulted in an irregular glaze and colour appearance. A cloudy effect with different coloured glaze layers was the result.

#recipe[
  One used several salts to reach the required colour shades. The origin of those compounds was not always clear, neither was the measure of radiation. For colouring of the glazes the mainly applied uranium compounds were:

  #align(center,
    table(
      columns: (1fr, 1fr),
      stroke: none,
      align: (left, left),
      table.header([*Name*], [*Formula*]),
      [Uranium dioxide], [$"UO"_2$],
      [Uranium trioxide], [$"UO"_3$],
      [Uranium oxide], [$"U"_3"O"_8$],
      [Sodium uranate], [$"Na"_2"O" dot "UO"_3$],
      [Sodium diuranate], [$"Na"_2"O" dot 2"UO"_3$],
      [hydrated sodium diuranate], [$"Na"_2"O" dot 2"UO"_3 dot 6"H"_2"O"$],
      [uranium nitrate], [$"UO"_2"(NO"_3")"_2 dot 6 "H"_2"O"$],
      table.hline(stroke: 0.5pt),
    )
  )
]

#recipe[
  Although not a red-giving composition but a main one in respect of the application of uranium for the well known greenish-yellowish fluorescence, the following composition is mentioned by Jochmann:

  #align(center,
    table(
      columns: (auto, auto),
      stroke: none,
      align: (left, right),
      [$"Na"_2"O"$], [12.80 %],
      [$"K"_2"O"$], [4.94 %],
      [$"CaO"$], [6.03 %],
      [$"BaO"$], [2.83 %],
      [$"As"_2"O"_3$], [0.21 %],
      [$"UO"_3$], [0.58 %],
      [$"SiO"_2$], [72.60 %],
      table.hline(stroke: 0.5pt),
      [], [99.99 %]
    )
  )
]

The uranium was introduced through sodium uranate. If the glass was melted under the proper oxidizing conditions it resulted in the required yellowish fluorescence.

In those cases the uranium should be present as $"UO"_3$.

#recipe[
  The early uranium red glazes mentioned by Binns and Lyttle were based on the following compositions:

  #align(center,
    table(
      columns: (auto, auto, 2em, auto, auto, 2em, auto, auto),
      stroke: none,
      align: (left, right, center, left, right, center, left, right),
      [$"K"_2"O"$], [0.12], [], [$"Al"_2"O"_3$], [0.12], [], [$"SiO"_2$], [1.33],
      [$"PbO"$], [0.80], [], [], [], [], [], [],
      [$"ZnO"$], [0.08], [], [], [], [], [], []
    )
  )
]

An addition of 20 % of sodium uranate should result in a cinnabar red glaze for SK04a (1020 °C).

#recipe[
  The base glaze:

  #align(center,
    table(
      columns: (auto, auto, 2em, auto, auto, 2em, auto, auto),
      stroke: none,
      align: (left, right, center, left, right, center, left, right),
      [$"K"_2"O"$], [0.04], [], [$"Al"_2"O"_3$], [0.12], [], [$"SiO"_2$], [0.79],
      [$"PbO"$], [0.87], [], [], [], [], [], [],
      [$"ZnO"$], [0.09], [], [], [], [], [], []
    )
  )
  together with an addition of 37 % sodium uranate resulted in a matt red glaze for SK 04a (1020 °C).
]

#recipe[
  Zimmermann mentioned the following compositions for orange-red glazes, suitable at SK 07a till SK 03a (960 °C till 1040 °C):

  #align(center,
    table(
      columns: (auto, auto, 2em, auto, auto, 2em, auto, auto),
      stroke: none,
      align: (left, right, center, left, right, center, left, right),
      [$"PbO"$], [1.00], [], [$"Al"_2"O"_3$], [0.175], [], [$"SiO"_2$], [0.4 -- 0.6],
      [], [], [], [], [], [], [], [],
      [$"K"_2"O"$], [0.10], [], [$"Al"_2"O"_3$], [0.175], [], [$"SiO"_2$], [0.85],
      [$"PbO"$], [0.90], [], [], [], [], [], [],
      [], [], [], [], [], [], [], [],
      [$"PbO"$], [0.90], [], [$"Al"_2"O"_3$], [0.175], [], [$"SiO"_2$], [0.60],
      [$"ZnO"$], [0.10], [], [], [], [], [], []
    )
  )
]

For these compositions counted that an addition of 20 parts of sodium uranate to 100 parts of base glaze was applied.

#recipe[
  The study of Eska is detailed and built up in a very schematic way. The glazes were fired at SK 08a (940 °C) and SK 05a (1000 °C). The below mentioned glazes gave, according to the author, good red glazes:

  #align(center,
    table(
      columns: (auto, auto, 2em, auto, auto, 2em, auto, auto),
      stroke: none,
      align: (left, right, center, left, right, center, left, right),
      [$"PbO"$], [1.00], [], [$"Al"_2"O"_3$], [0.10], [], [$"SiO"_2$], [1.40],
      [], [], [], [$"UO"_3$], [0.20], [], [], [],
      [], [], [], [], [], [], [], [],
      [$"BaO"$], [0.10 -- 0.20], [], [$"Al"_2"O"_3$], [0.10], [], [$"SiO"_2$], [1.20 -- 1.40],
      [$"PbO"$], [0.90 -- 0.80], [], [$"UO"_3$], [0.15], [], [], [],
      [], [], [], [], [], [], [], [],
      [$"PbO"$], [0.90 -- 0.80], [], [$"Al"_2"O"_3$], [0.10], [], [$"SiO"_2$], [1.20 -- 1.40],
      [$"ZnO"$], [0.10 -- 0.20], [], [$"UO"_3$], [0.20], [], [], []
    )
  )
]

#recipe[
  The weather resistance was not always sufficient and the glazes were heavily attacked. This as contrasted with glazes where the lead content was partly replaced by fluorspar:

  #align(center,
    table(
      columns: (auto, auto, 2em, auto, auto, 2em, auto, auto),
      stroke: none,
      align: (left, right, center, left, right, center, left, right),
      [$"CaF"_2$], [0.10], [], [$"Al"_2"O"_3$], [0.10], [], [$"SiO"_2$], [1.40],
      [$"PbO"$], [0.90], [], [$"UO"_3$], [0.15], [], [], []
    )
  )
]

This glaze should give an intensive and deep bright red colour. The surface of the glaze was a glossy one and the weather resistance was good.

If part of the lead content was replaced by magnesium the investigator observed an increased tendency for crazing and a matt surface.

#recipe[
  The introduction of potassium resulted in bright red glossy glazes with a good resistance. The following examples can be mentioned:

  #align(center,
    table(
      columns: (auto, auto, 2em, auto, auto, 2em, auto, auto),
      stroke: none,
      align: (left, right, center, left, right, center, left, right),
      [$"K"_2"O"$], [0.10 -- 0.20], [], [$"Al"_2"O"_3$], [0.10], [], [$"SiO"_2$], [1.60],
      [$"PbO"$], [0.90 -- 0.80], [], [$"UO"_3$], [0.15], [], [], []
    )
  )
]

A too high an amount of sodium had a negative influence on colour, glaze, surface and craze- and weather resistance. The sodium content may not exceed 0.10 mol while as preferable $"SiO"_2$ content is mentioned 0.40 mol to a maximum 0.80 mol.

#recipe[
  Kautz gives some compositions for respectively green, yellow, ivory, orange and red uranium based glazes. As possibility for a vermillion red glaze he mentioned:

  #align(center,
    table(
      columns: (auto, auto, 2em, auto, auto, 2em, auto, auto),
      stroke: none,
      align: (left, right, center, left, right, center, left, right),
      [$"Na"_2"O"$], [0.10], [], [$"UO"$], [0.20], [], [$"SiO"_2$], [2.00],
      [$"PbO"$], [0.90], [], [], [], [], [], []
    )
  )
]

#recipe[
  A good tomato red glaze for SK 07a (960 °C) with good processing properties is mentioned by Eggert. As base glaze was used:

  #align(center,
    table(
      columns: (auto, auto, 2em, auto, auto, 2em, auto, auto),
      stroke: none,
      align: (left, right, center, left, right, center, left, right),
      [$"PbO"$], [1.00], [], [$"Al"_2"O"_3$], [0.10], [], [$"SiO"_2$], [1.80]
    )
  )
]

The basic red glaze was made with an addition of 16.7 % black uranium oxide $"UO"_3$, this to avoid the simultaneous but unwanted sodium introduction. These glaze components were not fritted before, but applied as raw glazes. As components with a negative influence on both the red colour and the glaze appearance are mentioned: calcium carbonate, boric acid and rutile. A more matt surface was supported by the introduction of e.g. tin oxide (8 %), barium carbonate (5 %), tungsten acid (2 %) and molybdenum acid (2 %). Components which radiate a positive influence on the red colour are zinc oxide (8 %), magnesium oxide (5 %), lithium carbonate (5 %) and beryllium carbonate (2 %).

#recipe[
  Viehweger mentioned a fire-red, opaque matt glaze with following composition:

  #align(center,
    table(
      columns: (auto, auto),
      stroke: none,
      align: (left, right),
      [$"ZnO"$], [2.55 %],
      [$"PbO"$], [64.08 %],
      [$"Al"_2"O"_3$], [5.41 %],
      [$"SiO"_2$], [11.02 %],
      [$"Na"_2"U"_2"O"_7$], [16.94 %],
      table.hline(stroke: 0.5pt),
      [], [100.00 %]
    )
  )
]

#recipe[
  An orange-red opaque glaze for SK 05a -- 03a (1000 °C -- 1040 °C) had the following composition:

  #align(center,
    table(
      columns: (auto, auto),
      stroke: none,
      align: (left, right),
      [$"Na"_2"O"$], [3.81 %],
      [$"CaO"$], [5.35 %],
      [$"PbO"$ fritted], [24.38 %],
      [$"Al"_2"O"_3$], [5.04 %],
      [$"B"_2"O"_3$], [5.28 %],
      [$"SiO"_2$], [36.14 %],
      [$"UO"_3$], [15.00 %],
      [Kaolin], [5.00 %],
      table.hline(stroke: 0.5pt),
      [], [100.00 %]
    )
  )
]

Another application of uranium salts is also mentioned, namely in the composition of some coloured lustres. For this purpose one first made a resinate which is than dissolved in a colophony and various essential oils such as oleum rosmarini, oleum lavendular, oleum spicae, oleum foeniculi and others. Uranium nitrate was used to produce brilliant, iridescent lustres of a yellow colour. For the necessary uranium resinate one dissolved the uranium nitrate and soft soap in a separate way. The solutions were then poured together under the forming of a resinate. This resinate must be washed, air-dried and could then be used.

#recipe[
  A golden-yellow luster was then prepared using following composition:

  #align(center,
    table(
      columns: (auto, auto),
      stroke: none,
      align: (left, left),
      [uranium resinate], [25.0 parts],
      [colophony], [25.0],
      [benzene], [25.0],
      [oil of lavender], [25.0]
    )
  )
]

The colophony was first dissolved in the oil of lavender using moderate heat. Then the uranium resinate was added, followed by the benzene. After cooling the liquid was first filtered before it was stored in bottles.

Apart from that, Viehweger stated that it was no longer allowed to use uranium compounds in the ceramic sphere. The already before mentioned reasons were a cause that the application of these type of glazes felt into abeyance.

@photo:uranium-glaze shows the uranium glaze which is in all respect a specific one and therefore difficult to replace by other colouring compounds.

Nowadays we can only wonder that the use of these compounds was rather wide spread. Till the 2#super[nd] World War however, when all uranium compounds were claimed for nuclear investigations, it was a way to create orange and red ceramic colours which was impossible to do in another way. Still today, the glazes have a very good, nice and brilliant appearance. There are various examples in factory musea in several countries which I have seen and the tomato red colour was still impressive. An example is shown by @photo:uranium-glaze. It shows an uranium glaze made by the famous ceramic factory Mobach in Utrecht / The Netherlands. This and other uranium based glazes were made around 1930.

#figure(
  image("../assets/uranium-glaze.jpg", width: 60%),
  kind: "photo",
  supplement: [Photograph],
  caption: [Uranium red glaze. Courtesy of Mobach B.V., Utrecht, The Netherlands]
) <photo:uranium-glaze>

Another example is the Homer Laughlin factory in East Liverpool - Ohio / USA. They make the so-called Fiesta ware (dinnerware in earthenware) in various colours ever since 1936. It included at that time a red-orange colour which was made through a uranium red glaze (@photo:uranium-fiesta).

#figure(
  image("../assets/uranium-fiesta.jpg", width: 60%),
  kind: "photo",
  supplement: [Photograph],
  caption: [Uranium red glazes. Small plate produced by Homer Laughlin / USA. Other two items produced by Californian potteries. Between 1930 and 1940]
) <photo:uranium-fiesta>

In 2001 a comprehensive article was published by Donna Strahan#footnote[Donna Strahan. 'Uranium in Glass, Glazes and Enamels: History, Identification and Handling'. Studies in Conservation, Vol.46, nr.3, 2001.]. The article is a survey of over 400 glass, ceramic and enamel objects from museum and private collections. It is an investigation for the extent of uranium colorants, mainly produced between 1830 till 1940. It shows that uranium colorant was widely used in glass and ceramic and also that little health risk was found from the uranium containing objects.

#pagebreak()
