// Chapter 10 Section 5: Defects

#import "../../template.typ": ch

== Defects

Although they are coloured glazes, the group of cadmium selenium melted-in glazes is always prepared by the bigger glaze manufacturers. It is not a coloured glaze in the sense of adding a colour stain to a suitable transparent glaze to achieve the required colour. Only now, with the last generation of strong cadmium selenium stains it is indeed possible to add these (expensive) stains to a transparent glaze to achieve a strong yellow, orange or red colour. But the group of cadmium selenium glazes meant here are the so-called melted-in glazes. The glazes create their final colour out of the special composed frits which contain the colour-giving components. The glazes are made ready-to-use by the manufacturers which mean that only water needs to be added. They normally contain Westerwalder clay or ball clay, kaolin and / or bentonite to prevent the glaze from settling down. As these glazes have a rather high amount of alkali, it is to be advised to prepare only the amount of glaze necessary for a job to do or an amount which will be finished during a working day. In case some settling should appear the normal setting up agents as calcium chloride or magnesium chloride can be used to keep the glaze in suspension.

The group of cadmium selenium glazes sometimes shows some defects which are more or less typical for these glazes. Especially for the melted-in cadmium selenium glazes counts that they must meet certain requirements with regard to the composition for a good colour development. These requirements results e.g. in a substantial amount of alkali components (mostly sodium) resulting in a rather high thermal coefficient of expansion (c.o.e.) with a typical figure of ($3alpha$) 210 to 240 $times 10^(-7)$ for these glazes. The result is that most of the cadmium selenium glazes show crazing at the normal applied earthenware and stoneware type of bodies. Only during the 70ties and when the demand for red-glazed articles was that high, some manufacturers applied a special body with increased coefficient of expansion resulting in a craze free red glaze. In many other cases the inside of vases was and is glazed in such a way that the inside glaze was not crazing and therefore not leaking when the vase was filled up with water. This procedure is still applied today e.g. for flower vases where a cadmium selenium red glaze is applied on the outside and a transparent semi-matt glaze is applied on the inside. Application of the glazes is done by automatic spraying machines on the pressed and dried body and the articles are subsequently once fired at about 1050 °C.

Extensive investigations have been made during the 70ties for the development of a craze free red glaze starting from the frits. Trials to lower the thermal c.o.e. of the glaze were focused on (i) lowering the c.o.e. of the basic selenium-sulphur frit; (ii) lowering the c.o.e. of the basic cadmium frits and (iii) lowering of the c.o.e. of the low cadmium containing transparent supporting frit. The average thermal c.o.e. ($3alpha$) for a cadmium selenium red glaze is 220 $times 10^(-7)$. Target was a c.o.e. of about 180 $times 10^(-7)$.

However, it is possible to obtain similar good results for the red glaze characteristics by lowering the c.o.e. of one of the composing frits (i, ii or iii) but as soon as all basic and necessary frits (i, ii and iii) are modified to lower c.o.e. versions, the characteristics of the red glaze changes. In most cases it resulted in glazes which were too hard and/or had a too short a maturing range.#super[@lit:l-w-baaij] This was the reason that one stayed with the standard red glazes which had been accepted by the market knowing that crazing was simply an unavoidable characteristic property of the glazes. What often was done to decrease the c.o.e. of the cadmium selenium red glazes was an addition of a zircon white frit with a c.o.e. of approx. 168 $times 10^(-7)$ or a suitable lead free transparent frit, also with a c.o.e. of approx. 168 -- 170 $times 10^(-7)$. Also additions of a frit with an extreme low c.o.e. were applied.

Such additions to red glazes (up to 15 parts) helped to decrease the c.o.e. but the glazes were in most cases not craze resistant to a Harkort test.

Another phenomenon which occurred at the production of e.g. red glazed vases but also tiles was blistering; quite an amount of open and closed craters on the glaze surface often together with matt spots or matt areas. The defect appeared very often at only one side of the fired articles and a closer inspection often learned that it was always the place where the gases passed the articles, in any case places with a less good ventilation. Changing and improving the ventilation in the kiln (more volumes of air) normally improved and prevented those defects. Also a more open setting is helpful although there is a loss of capacity in that case.

A rather open setting and enough ventilation is even more important when more organic compounds are involved e.g. in a decoration firing. In such cases all the organics has to be burned off before the glaze matures. In case of less good ventilation this may cause problems resulting in pinholes and/or small bubbles. The reason can be that for the printing media and the cover coat often poly acrylate resins are used. Most of these components start to decompose at 360 °C at which temperature gases are formed from these organic materials which must be removed from the kiln as soon as possible. If not enough air/oxygen is available to remove these organic gases, the vapour pressure is increasing in the first part of the kiln which may result in pinholes and small bubbles. For a complete burning off of one gram of these polymers one needs about 10 liter of air/oxygen.#super[@lit:f-x-leipold] This makes clear that a good ventilation and a more open setting is very important in firing cadmium selenium red glazes.

A typical defect for cadmium yellow and cadmium selenium red and orange glazes are also the black or brown spots visible in the fired glaze and destroying the nice warm and uniform colour of the article. The root cause of this defect is in almost all cases small metal or metal oxide impurities. A reason can be a contamination of the body by small metal or metal oxide parts (like pyrite). It is also possible that a piece of production equipment e.g. for the glaze preparation (stirrer, sieves, pumps, etc.) shows too much wearing resulting in small metal parts coming into the glaze slip. A magnet can prevent further damage and clean up the glaze. In case of copper metal particles this is, however, not possible. Many of these dark coloured spots have been investigated by making a cross section of the fired piece and investigating the particular spot with the help of XR-F. In the majority of these cases the observations using an optical microscope learned that the contamination was in most cases originated from the body and that it was confirmed by XR-F analyses that #ch("Fe") in most cases was the reason for the dark coloured spot.

Sometimes transparent colourless rims appeared, especially the rather sharp rims of cups and saucers. As an explanation for these phenomena is given that soluble salts are moving to the rims after application of the glaze and when the glaze is still wet. Drying of the article starts from the rims so the moisture goes from the mid parts of the article to the rim taken the soluble salts with it. The moisture disappears at the rim leaving the salts behind. Those places with higher concentrations of soluble salts will result in a lower surface tension of the glaze and therefore a thinner glaze layer after firing. In this thinner glaze layer the red colour will disintegrate and a colourless layer appears.

Some red and yellow glazes, not all, sometimes showed a white film over the glaze after firing. This white film is also caused by salts like sodium sulphate which have moved to the surface area during drying of the articles while the glaze is still in a wet state. In these cases an addition of a barium salt to the glaze slip helps to prevent the white film.
