// Chapter 10 Section 6: Vein Structure

#import "../../template.typ": ch

== Vein structure

Another aspect of the melted-in cadmium selenium glazes versus the pigmented glazes are the so-called veins in the glaze. The melted-in cadmium selenium glazes always have a more or less cloudy appearance while the pigmented red glazes more look like a lacquer red. These veins are sometimes visible with darker rims. Some glazes have an outspoken vein structure, some less. This has mainly to do how the glaze is built up. The composition of the glaze as well as the firing cycle have an influence on the final appearance of the glaze and the vein-structure. As contrasted with the melted-in glazes, the pigmented type of red glazes never show this phenomenon. If one prepares cross-sections of the fired glaze and have a closer look with an optical microscope one can determine that the veins are in fact transparent 'canyons' formed between the 'clouds' of the red glaze. The darker parts of the veins are in most cases caused by a shadowing effect. These darker coloured striations are generally located on ridges or overhangs of canyons of clear glass between the 'clouds' of the red coloured glaze. It can also be noticed that in many cases the top layer of the glaze is transparent as also the intermediate layer between glaze and body. This effect is more clear and visible if one goes to the high end of the firing range of a given glaze. Investigations using XR-F analyses have been done on the transparent, clear glass parts, the canyons so to speak. The measurements were done for #ch("Ba"), #ch("Cd"), #ch("Se"), #ch("Pb") and #ch("Zn"). The first measurements were done on the glaze surface with only a few microns depth. After these first measurements the surface of the glaze was progressively ground off and polished after which the same elements were analysed again. When the measured amounts of the elements were plotted against the depth of the glaze it was clearly shown that the amounts for #ch("Ba"), #ch("Pb"), #ch("Zn") and #ch("Cd") were the same for all depths but that the amount of #ch("Se") was increasing with every measured depth till the level of 25 to 30 microns. From that depth the measured amount of #ch("Se") followed a horizontal line. This meant that the #ch("Se") clearly had evaporated from the surface.#super[@lit:report-rc-15971-ferro]

Literature learns that the loss of #ch("Cd"), #ch("S") and #ch("Se") from glasses is controlled by the chemical potential of oxygen in the glass. Both #ch("Zn") and #ch("S") act as redox buffers that help maintain a stable chemical potential. If the chemical potential is too low (glass too reduced), excessive amounts of #ch("Cd") will be lost, while if too high (glass too oxidized), selenium will be rapidly volatilized.

Cadmium selenium melted-in red, orange and yellow glazes are always multi-fritted glazes. The selenium containing frit is melted under moderate reducing conditions to minimize the volatilization of the selenium and thus fixing the chemical potential on a fairly low level. The cadmium containing frit (or frits), however, are melted under oxidizing conditions using sodium nitrate as one of the frit raw materials. These frits may thus be highly oxidized (high oxygen chemical potential). When the glaze is fired its chemical potential will adjust eventually to the average value of the various frits of the glaze. The fact that #ch("Se") has been lost from the surface layer and that the #ch("Cd") is stable suggests that the resulting chemical potential was too high (glaze too oxidizing). The selenium is most probably lost before the glaze has reached its transformation point. A way to reduce the effect of vein structure in red glazes is therefore to reduce the amount of high oxidized melted frits or to introduce frits which are melted in a more neutral way.

With the above mentioned knowledge it is possible to 'adjust' the composition of red, orange and yellow melted-in cadmium selenium glazes in such a way that a less pronounced vein structure is the result. The firing stability at higher firing temperatures and colour strength of the glazes are however more important for a manufacturer than, in most cases, a nice 'cloudy' effect with some vein structure. If one doesn't like this typical structure of melted-in glazes there is now a way to overcome this with the 3rd generation of encapsulated #ch("CdSe") pigments which are suitable to fire at high temperatures and give a more lacquer appearance.
